### PR TITLE
fix(fromOpenApi): support subdirectories in the server URL

### LINKED ISSUE #58: Subdirectory on a Server Object’s url field is getting cut off
## Description

The subdirectory on a Server Object’s url field is getting cut off.

[from-open-api.ts#L55-L57](https://github.com/mswjs/source/blob/main/src/open-api/from-open-api.ts#L55-L57)
```ts
const requestUrl = isAbsoluteUrl(baseUrl)
                    ? new URL(path, baseUrl).href
                    : joinPaths(path, baseUrl);
```

## Reproduction steps

api-schema.json
```json
"servers": [
    {
      "url": "https://example.com/web"
    }
  ],
  "paths": {
    "/api/v1/whoAmI": {
      "get": {
        "summary": "Who am I",
        "description": "",
        "operationId": "whoAmI",
        "responses": {
          "200": {
            ...
          }
        }
      }
    }
  },
```

The requestUrl const = `https://example.com/api/v1/whoAmI`

## Expected behavior

The requestUrl const should = `https://example.com/web/api/v1/whoAmI`

## Initial assessment

The path should be appended to the Server Object’s url field in order to construct the full URL.  Calling `new URL()` is how it's getting cut off.

## Screenshots

image

### PR DESCRIPTION
**Pull request by jimmymcpeter**
Fixes #58

### CODE REVIEW

**Review by weyert — APPROVED** [review]

File: src/open-api/from-open-api.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ export async function fromOpenApi(
       for (const baseUrl of serverUrls) {
         const path = normalizeSwaggerUrl(url)
         const requestUrl = isAbsoluteUrl(baseUrl)
-          ? new URL(path, baseUrl).href
```
Comment (kettanaito) [inline src/open-api/from-open-api.ts:56]: So, the subdirectory gets cut off because we've constructed the URL incorrectly. Specifcally, the `path` must always ends with a trailing slash. 

That would be the fix. Could you please adjust the pull request for that?

**Review by kettanaito — CHANGES_REQUESTED** [review]
Hey, @jimmymcpeter 👋 Thank you so much for fixing this! (and for adding a test case)

I've left one comment that I believe can make the solution better. There's no need for us to drop the way `URL` handles base path, that wasn't the problem. The problem was that we never ensured the `path` value ends with a trailing slash. That broke the subdirectories.

**Comment by jimmymcpeter** [comment]
Hi, maybe I'm confused but I was trying to follow the OAS for [paths](https://spec.openapis.org/oas/v3.0.3#paths-object)
>A relative path to an individual endpoint. The field name MUST begin with a forward slash (/). The path is appended (no relative URL resolution) to the expanded URL from the Server Object’s url field in order to construct the full URL

**Comment by kettanaito** [comment]
My bad, got things confused. There are two key points to solving this:

1. The server URL must end with a trailing slash.
2. The `path` segment must start with a dot to denote relative path to the _full_ server URL.

```js
new URL('/bar', 'https://example.com/foo')
// https://example.com/bar

new URL('./bar', 'https://example.com/foo/')
// https://example.com/foo/bar
```

**Comment by jimmymcpeter** [comment]
I'm curious why not just append the path to the server URL like the spec says?  It shouldn't be doing any URL resolution, which is what URL() does when you pass a [base parameter](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#base) to it

**Comment by kettanaito** [comment]
@jimmymcpeter, behavior-wise, there should be no difference. I just prefer using the `baseURL` argument of `URL`, but in this case it may redundant, I agree. 

I wish URL handled double slashes `//` but those are legitimate URL tokens.

**Review by kettanaito — APPROVED** [review]
Thanks for the discussion, @jimmymcpeter! This looks good to me. Let's merge it.

**Comment by kettanaito** [comment]
## Released: v0.2.1 🎉

This has been released in v0.2.1!

- 📄 [**Release notes**](https://github.com/mswjs/source/releases/tag/v0.2.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/source/v/0.2.1)

Make sure to always update to the latest version (`npm i @mswjs/source@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
